# Generated by Django 2.0.1 on 2018-01-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webzinedown',
            old_name='files',
            new_name='file',
        ),
    ]
